[package]
name = "cargo-saddle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bstr = { version = "1.6.2", default-features = false }
clap = { version = "4.4.2", features = ["derive"] }
color-backtrace = "0.6.0"
memchr = "2.6.3"
petgraph = "0.6.4"
rustc-hash = "1.1.0"
